New corrections
izabelanowak/movies-browser pull request #19
Opened 2021-08-19 11:30 UTC by krystian-kazmierczak

I fixed some bugs: navigation, favicon, margin in Rating and displaying image in ProfilePage. 
It's not much, but I think it looks better now.
If you don't have suggestions then I would merge it in `develop`.

2021-08-19 12:44 UTC, Kinga-parasiewicz approved these changes
Very good job, maybe could you correct navigation?  we told about that

2021-08-19 17:05 UTC, krystian-kazmierczak commented
I'm still working on it. 
I not quite like the look of it and I'm still looking good solution. 
I think part of the problem may be with the user's monitor displaying the website and we cannot fix this.

2021-08-19 21:47 UTC, izabelanowak requested changes
I added a few comments from myself.
Great job 😃  but it still needs to be improved a bit.

2021-08-19 21:47 UTC, izabelanowak commented on public/favicon.svg
> +<svg width="40" height="40" viewBox="0 0 40 40" fill="transparent" xmlns="http://www.w3.org/2000/svg">
Icon looks much better now!

2021-08-19 21:47 UTC, izabelanowak commented on src/Navigation/Link/styled.js
>    &.${activeClassName} {
Now it looks better, but after pressing button border jumps strangely. It's hard to describe, I attach a gif showing what I mean.
![outline](https://user-images.githubusercontent.com/83245340/130147421-7a3239a1-3c16-4304-a4b0-97f44bea32a8.gif)

2021-08-19 21:47 UTC, izabelanowak commented on src/features/PeoplePage/index.js
>                    key={person.id}
Images looks perfect now 😄

2021-08-19 21:47 UTC, izabelanowak commented on src/common/Rating/styled.js
> +  margin: 12px 0;
I think we should add only margin-top to 12px and rest set to 0.

2021-08-19 21:47 UTC, izabelanowak commented on src/Navigation/Link/styled.js
>    padding: 14px 16px;
In this file I see one more error (we could forget about it before) there is missing curly bracket after
`@media (max-width: ${({ theme }) => theme.breakpoints.mobile}px) {
    padding: 0;
    gap: 8px;
`;`
please add it when you make corrections

2021-08-19 21:47 UTC, izabelanowak commented on src/common/Tile/styled.js
>  export const Image = styled.img`
If you changed height to auto in main `Image` style, you can delete other ` height: auto;` 😄 just a small note not to duplicate the same code 😃

2021-08-20 10:06 UTC, izabelanowak approved these changes
Ok, you can merge.

2021-08-20 10:07 UTC, izabelanowak approved these changes
Ok, you can merge.

2021-08-20 10:14 UTC, merged